# This is the network config written by 'subiquity'
network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      addresses:
        - 192.168.1.44/24
      gateway4: 192.168.1.1
     # dhcp6: true
      nameservers:
          addresses: [9.9.9.9]
    enp3s0:
      addresses:
        - 10.0.0.1/24
        - fdb1:3d0e:7458:1f46:0:0:0:1/128
